### ISSUE TITLE
3dparty jar alias

### ISSUE THREAD

**Issue by pvrhijn** [fastconnect/tibco-factory#2]
Hi,

I'm trying to configure a maven projlib with sftp(I use an sftp palette). Therefore I have to create an AliasLibrary for the jsch-20070510.jar file.
I have the mentioned jar file as an artifact in nexus, but when I configure this jar as a dependency in the pom the aliasname in designer is com.tibco.bw:jsch-20070510:1.0.0:jar and the saved jar file is named jsch-20070510-1.0.0.jar.

The SFTP palette doesn't recognize these names. It has to be the normal jar filename.
How can I solve this?

Thanks in advance.

Patrick van Rhijn

**Comment by pvrhijn** [comment]
I'v found that a build keeps Aliases you defined yourself in a AliasLibrary that is located in the tibco project root folder.

But is there also a way to define a FileAlias and persist this value during a build?

**Comment by mledoujet** [comment]
For info, the aliases are defined in a file called Designer5.prefs in the user directory ( C:\Users\<USER>\.TIBCO ).
the projlib or jars aliases should be defined there as below
filealias.pref.1=FCUnit.jar\=J:\Projets\trunk\library-1.4.0-SNAPSHOT.jar.

If you can't do what you want with the framework, maybe you should be able to do so in ksh or bat.
by updating content, and updating the desinger.pref file with correct value

**Comment by debovema** [comment]
First, BWMaven will _not_ use the File Aliases of Designer5.prefs (it will create a copy of this file and remove any File Aliases entry to ensure the build does not depend on the platform).

Can you give the version of SFTP plugin you are using and if possible its configuration (description or screenshot) ?

**Comment by pvrhijn** [comment]
Hi,

I also want to be able to work platform independently, because we will try to move to automated builds.

I use a custom pallet from a 3d party. It's pretty old and depends on jcraft (java implementation of ssh2). 
![sftp-palette](https://cloud.githubusercontent.com/assets/6949061/13785547/4913e4a4-ead4-11e5-8589-d2d6c2fb5fb7.PNG)

I don't know about the properties.

I tested localy with a altered AbstractBWMojo.java and the folowing does work for me.

protected String getJarAlias(Dependency jarDependency, boolean replaceDot) {
        assert (jarDependency != null);
        String version = jarDependency.getVersion();
        if (replaceDot) {
            version = version.replace('.', '_');
        }

```
    return jarDependency.getArtifactId() + "." + JAR_TYPE;
}
```

I'm not sure if I ever need the full groupId:artifactId:version.jar as an alias. It has to reference to the proper version jar file, but the alias name can be just the artifactId.

I don't know your idea behind the full aliasname.

**Comment by debovema** [comment]
Hi,

The full alias name is to ensure uniqueness based on Maven model (BWMaven is aimed at enabling TIBCO BW lifecycles in Maven according to its model and precepts).

Concerning your issue, considering this 3rd party palette really needs a custom filename for the JAR dependency, I suggest that you use a goal from a standard Maven plugin such as [dependency:copy](https://maven.apache.org/plugins/maven-dependency-plugin/copy-mojo.html) to copy the JAR with a custom filename.

Regards,

Mathieu

**Comment by pvrhijn** [comment]
Hi,

As far as I can tell the dependency:copy only places the jar file on a specific location, but designer has no way of knowing where the jar file is.
I can also solve it by adding the jar file to the designer class path(and runtime to the application class  path).

**Comment by debovema** [comment]
Hi,

It's hard to reproduce without the 3rd party plugin.
The JAR is more likely to be added in the classpath (of Designer and in your target environment) instead of being managed by File Aliases. This is the way the [official SFTP plugin](https://docs.tibco.com/products/tibco-activematrix-businessworks-plug-in-for-sftp-1-1-0) works.

As a consequence I will close this issue. Feel free to open another directly on [BWMaven project](https://github.com/fastconnect/tibco-bwmaven/issues/new) or directly a pull request if you think that a new feature or improvement is required.

Regards,

Mathieu

**Comment by pvrhijn** [comment]
Thanks!

I've found the official plugin and we will use the classpath solution for our 3dparty palette until we migrate to this official plugin.

Next time I will use the proper project when reporting an issue.

Regards,

Patrick
